### ISSUE TITLE
Garmin - Madeira Island map?

### ISSUE THREAD

**Issue by fabioneves** [freizeitkarte/freizeitkarte-osm.de#1]
Hello,

Is it possible to have Madeira Islands map for Garmin devices? I saw that you have Portugal and Azores Islands maps, but not from Madeira.

Thanks a lot! Great job :)

**Comment by keenonkites** [comment]
Fábio,

Madeira is part of Portugal map... I know that for sure because I'm having holiday there this autumn and therefore already used that map for preparations...
;-)
Thanks for the flowers.

Cheers
Patrik

**Comment by fabioneves** [comment]
I thought it would be part of Portugal, but as you had Azores as a separate file, then I got my mind set that we needed a Madeira Islands map hehe.

Hey, that's awesome! I hope you'll enjoy your stay here, if you need any tips or any information at all I'm at your service.

Cheers!

**Comment by keenonkites** [comment]
thanks for the offer.... probably coming back to the offer later, I'm not that far with the planning yet.

I will close this issue, assuming it's solved.
Cheers
Patrik
